### ISSUE TITLE
came across this issue,anyone give some hints?

### ISSUE THREAD

**Issue by xiaods** [concourse/baggageclaim#2]
```
cmd/src/github.com/concourse/baggageclaim/volume/docker_image_strategy.go:40: cannot use strategy.Repository (type string) as type reference.Named in argument to client.NewRepository:
	string does not implement reference.Named (missing Name method)
```

**Comment by xoebus** [comment]
Looks like the Docker dependency has changed their API. Make sure you're working in `baggageclaim` inside the [concourse/concourse][https://github.com/concourse/concourse] repository to guarantee the correct dependency versions.

**Comment by xiaods** [comment]
@xoebus thanks for your hints.
