### ISSUE TITLE
Typo in test

### ISSUE THREAD

**Issue by thokari** [concourse/baggageclaim#4]
https://github.com/concourse/baggageclaim/blob/master/api/volume_server_test.go#L499
should probably be "can be destroyed". Just noticed this by chance, probably not worth a pull request.

**Comment by vito** [comment]
worth a PR to us!

**Comment by thokari** [comment]
Here you go ;)
https://github.com/concourse/baggageclaim/pull/5

**Comment by vito** [comment]
thanks :)
